import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Jadwal Tugas Kuliah",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen overflow-x-hidden">
        {children}
      </body>
    </html>
  );
}
